export const REQUEST_INTERVAL = 15000;

export const API_NAMES = [ 
    "accounts", 
    "assets", 
    "customers",
    "datapoints", 
    "devices", 
    "documents", 
    "forms", 
    "invites",
    "media", 
    "messages", 
    "namespaces", 
    "orders", 
    "patients", 
    "relationships", 
    "rules", 
    "templates",
    "users", 
    "workflows",
];

export const apiArray = [
    {hostname: "Nombre de la API", status: "healthy", date: new Date()},
    {hostname: "Nombre de la API", status: "healthy", date: new Date()},
    {hostname: "Nombre de la API", status: "roto", date: new Date()},
    {hostname: "Nombre de la API", status: "roto", date: new Date()},
    {hostname: "Nombre de la API", status: "healthy", date: new Date()},
    {hostname: "Nombre de la API", status: "healthy", date: new Date()},
    {hostname: "Nombre de la API", status: "roto", date: new Date()},
    {hostname: "Nombre de la API", status: "roto", date: new Date()},
    {hostname: "Nombre de la API", status: "healthy", date: new Date()},
    {hostname: "Nombre de la API", status: "healthy", date: new Date()},
    {hostname: "Nombre de la API", status: "roto", date: new Date()},
    {hostname: "Nombre de la API", status: "roto", date: new Date()},
    {hostname: "Nombre de la API", status: "healthy", date: new Date()},
    {hostname: "Nombre de la API", status: "healthy", date: new Date()},
    {hostname: "Nombre de la API", status: "roto", date: new Date()},
    {hostname: "Nombre de la API", status: "roto", date: new Date()},
]